### ISSUE TITLE
Windows binaries are not uploaded into github.

### ISSUE THREAD

**Issue by theLoDD** [vulkanchain/vulkan#1]
The title talks as it is. I may not mine vulcan because i may not download wallet for windows.

**Comment by vulkanchain** [comment]
Windows wallet is now available on releases page.

**Comment by Hushg2** [comment]
Hello @theLoDD  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)
